### ISSUE TITLE
User can create more then one voting (!!!)

### ISSUE THREAD

**Issue by pavkahanov** [Neos1/vo_main#101]

**Comment by pavkahanov** [comment]
It happend when @pzyryanov1995 find bug, where in created by voting question, app cannot find hints for this. It allow to create new voting without closing existing voting

**Comment by pavkahanov** [comment]
Now user can't create this, cause in app, before showing right panel with dropdown, showing loader and if loading process will be crashed, loader will stay on place.

**Comment by Stablex** [comment]
Fix this in smartcontracts
