### ISSUE TITLE
adding new project by address (preloader bug)

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#106]

**Comment by pzyryanov1995** [comment]
Add new project with this contract address 0xd0a6E6C54DbC68Db5db3A091B171A77407Ff7ccf
Get this:
![Screenshot_31](https://user-images.githubusercontent.com/25167303/60883435-67a0ac80-a274-11e9-88f4-fc35b52acd8e.png)

After click by ok, preloader not hide. Get infinite loading

**Comment by pavkahanov** [comment]
fixed
