### ISSUE TITLE
Button not interactive.

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#20]
Button back with screen size changed button not in all inner space interactive.

Когда делаешь размер экрана приложения меньше определенного размера, то кнопка при наведении не везде подсвечивается (клики по ней соответственно тоже не обрабатываются)
![Screenshot_1](https://user-images.githubusercontent.com/25167303/56792727-6db9ec00-6834-11e9-92fe-501140fb9bed.png)

**Comment by pzyryanov1995** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/25167303/56793064-4adc0780-6835-11e9-8bb1-5562ed0ae535.png)
Interactive only in red border area

**Comment by pavkahanov** [comment]
fixed
