### ISSUE TITLE
Freeze Adding shareholders progress

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#30]
Complete all steps, but on last progress freeze.
In console got this errors:

`Error: Returned error: insufficient funds for gas * price + value`

`errors.js:29 Uncaught (in promise) Error: Returned error: invalid argument 0: hex string has length 0, want 64 for common.Hash`

**Comment by pzyryanov1995** [comment]
It's problem for new wallet added manually. Balance for this user is 0

**Comment by pavkahanov** [comment]
fixed
