### ISSUE TITLE
Create pass. Keyboard layout lang incorrect

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#33]
![Screenshot_2](https://user-images.githubusercontent.com/25167303/56802334-f68f5280-6849-11e9-9d76-b99c9a65b8f3.png)
Should be rus, but show eng

**Comment by pavkahanov** [comment]
@pzyryanov1995 This is not keyboard layout. This is one of parameters for password, which checking by regex. If password will be contain letters from other alphabets, this will be marked by grey color. If password language will be correct, it will be blue
