### ISSUE TITLE
Strange password change

### ISSUE THREAD

**Issue by Jenya8** [Neos1/vo_main#4]
![image](https://user-images.githubusercontent.com/46047748/51524700-46ccd200-1e61-11e9-9cd8-7bb9aede2a71.png)
That happened after pass change

**Comment by Jenya8** [comment]
![image](https://user-images.githubusercontent.com/46047748/51524793-754aad00-1e61-11e9-9042-04b44e718687.png)

**Comment by pavkahanov** [comment]
that's happens when passphrase is invalid (contains spaces or invalid words)
