### ISSUE TITLE
Crash app on select

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#40]
![Screenshot_3](https://user-images.githubusercontent.com/25167303/58408645-66d30300-8098-11e9-8af3-818bccffcea3.png)
![Screenshot_4](https://user-images.githubusercontent.com/25167303/58408654-69355d00-8098-11e9-8005-34ccf4069243.png)
![Screenshot_5](https://user-images.githubusercontent.com/25167303/58408656-6a668a00-8098-11e9-8d08-050f5099642b.png)
![Screenshot_6](https://user-images.githubusercontent.com/25167303/58408658-6b97b700-8098-11e9-9dbe-fce6c1832e23.png)

**Comment by pavkahanov** [comment]
fixed
