### ISSUE TITLE
Incorrect sort by date

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#42]
New questions should be displayed first.

**Comment by pavkahanov** [comment]
fixed

**Comment by pzyryanov1995** [comment]
When selecting by date, sorting also does not apply
27.04 then 24.04 then 27.04

![Screenshot_4](https://user-images.githubusercontent.com/25167303/58410770-10b48e80-809d-11e9-9352-a31234eacb39.png)
![Screenshot_5](https://user-images.githubusercontent.com/25167303/58410779-13af7f00-809d-11e9-9679-19412d28c5c1.png)
