### ISSUE TITLE
Start voting from questions, incorrect index

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#43]
Example:
Choice 3rd question

![Screenshot_6](https://user-images.githubusercontent.com/25167303/58412974-d994ac00-80a1-11e9-8698-00ec3d320f73.png)

But in select 2 choosed
![Screenshot_7](https://user-images.githubusercontent.com/25167303/58413018-ef09d600-80a1-11e9-85b9-275ec8a9234c.png)

**Comment by pavkahanov** [comment]
fixed
