### ISSUE TITLE
Modal voting submti caused log out

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#47]
On submit
![Screenshot_12](https://user-images.githubusercontent.com/25167303/58413939-2ed1bd00-80a4-11e9-9c35-8ed83365399a.png)

get this screen

![Screenshot_13](https://user-images.githubusercontent.com/25167303/58413980-427d2380-80a4-11e9-89c4-59226a46e6fd.png)

**Comment by pavkahanov** [comment]
fixed
