### ISSUE TITLE
Connect new project bug

### ISSUE THREAD

**Issue by pzyryanov1995** [Neos1/vo_main#85]
http://prntscr.com/oaxxey

**Comment by pzyryanov1995** [comment]
when add new project with incorrect address contract.
No validation!

**Comment by pzyryanov1995** [comment]
also infinite loop after adding address!
http://prntscr.com/oay1v3

**Comment by pavkahanov** [comment]
> also infinite loop after adding address!
> http://prntscr.com/oay1v3

This is not infinite loop, just low gas price
